name: Trigger auto deployment for blackjack

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'BlackJackServer/**'
    - '.github/workflows/blackjack-AutoDeployTrigger-b89e8ab0-57cb-4927-911c-ad43d3ee10ab.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ssscon.azurecr.io
          username: ${{ secrets.BLACKJACK_REGISTRY_USERNAME }}
          password: ${{ secrets.BLACKJACK_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ssscon.azurecr.io/blackjackserver:${{ github.sha }}
          file: BlackJackServer/Dockerfile
          context: BlackJackServer/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.BLACKJACK_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n blackjack -g sss-con-app-adventureserver-rg --server ssscon.azurecr.io --username  ${{ secrets.BLACKJACK_REGISTRY_USERNAME }} --password ${{ secrets.BLACKJACK_REGISTRY_PASSWORD }}
            az containerapp update -n blackjack -g sss-con-app-adventureserver-rg --image ssscon.azurecr.io/blackjackserver:${{ github.sha }}
